<?php
$parameters = array(
    'db_driver' => 'pdo_mysql',
    'db_host' => 'mautic-db',
    'db_port' => 3306,
    'db_name' => 'mautic',
    'db_user' => 'mautic',
    'db_password' => 'mautic_secure_2025',
    'db_table_prefix' => null,
    'db_backup_tables' => 1,
    'db_backup_prefix' => 'bak_',
    'db_server_version' => '10.6.0',
    'mailer_transport' => 'smtp',
    'mailer_host' => 'localhost',
    'mailer_port' => 25,
    'mailer_user' => null,
    'mailer_password' => null,
    'mailer_encryption' => null,
    'mailer_auth_mode' => null,
    'secret_key' => '3d7e3db9c8d46dc8e27ce5f3c5f3d0e3d3d3e3e3e3d3e3e3d3e3e3e3d3e3e3',
    'site_url' => 'http://localhost:8084',
    'api_enabled' => true,
    'api_enable_basic_auth' => true,
);