#!/bin/bash

# 🧹 Design System Maintenance Script
# Purpose: Clean up empty workflows and reorganize repository structure
# Date: 15 Août 2025
# Version: 1.0.0

echo "🚀 Starting Design System Cleanup..."
echo "=================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Counter for operations
DELETED_COUNT=0
MOVED_COUNT=0
ERRORS=0

# List of empty workflow files to delete
EMPTY_WORKFLOWS=(
  ".github/workflows/.gitkeep"
  ".github/workflows/auto-fix-deps.yml"
  ".github/workflows/auto-publish-v040.yml"
  ".github/workflows/fix-and-publish.yml"
  ".github/workflows/force-publish.yml"
  ".github/workflows/manual-publish.yml"
  ".github/workflows/npm-monitor.yml"
  ".github/workflows/publish-manual.yml"
  ".github/workflows/publish-ui.yml"
  ".github/workflows/quick-npm-publish.yml"
  ".github/workflows/simple-publish.yml"
  ".github/workflows/ui-100-coverage-publish.yml"
)

# Files to move
declare -A FILES_TO_MOVE=(
  [".github/workflows/EMERGENCY_AUDIT.sh"]="scripts/emergency-audit.sh"
  [".github/workflows/MAINTENANCE_LOG.md"]="docs/maintenance-log.md"
)

echo -e "${YELLOW}📊 Audit Summary:${NC}"
echo "- Empty workflows to delete: ${#EMPTY_WORKFLOWS[@]}"
echo "- Files to move: ${#FILES_TO_MOVE[@]}"
echo ""

# Function to delete empty workflows
delete_empty_workflows() {
  echo -e "${YELLOW}🗑️  Deleting empty workflows...${NC}"
  
  for file in "${EMPTY_WORKFLOWS[@]}"; do
    if [ -f "$file" ]; then
      # Check if file is actually empty
      if [ ! -s "$file" ]; then
        rm -f "$file"
        if [ $? -eq 0 ]; then
          echo -e "${GREEN}✅ Deleted: $file${NC}"
          ((DELETED_COUNT++))
        else
          echo -e "${RED}❌ Failed to delete: $file${NC}"
          ((ERRORS++))
        fi
      else
        echo -e "${YELLOW}⚠️  File not empty, skipping: $file${NC}"
      fi
    else
      echo -e "${YELLOW}ℹ️  File not found: $file${NC}"
    fi
  done
}

# Function to move misplaced files
move_misplaced_files() {
  echo -e "${YELLOW}📁 Moving misplaced files...${NC}"
  
  for source in "${!FILES_TO_MOVE[@]}"; do
    destination="${FILES_TO_MOVE[$source]}"
    
    if [ -f "$source" ]; then
      # Create destination directory if it doesn't exist
      dest_dir=$(dirname "$destination")
      mkdir -p "$dest_dir"
      
      # Move the file
      mv "$source" "$destination"
      if [ $? -eq 0 ]; then
        echo -e "${GREEN}✅ Moved: $source → $destination${NC}"
        ((MOVED_COUNT++))
      else
        echo -e "${RED}❌ Failed to move: $source${NC}"
        ((ERRORS++))
      fi
    else
      echo -e "${YELLOW}ℹ️  Source file not found: $source${NC}"
    fi
  done
}

# Function to validate remaining workflows
validate_workflows() {
  echo -e "${YELLOW}🔍 Validating remaining workflows...${NC}"
  
  local valid_count=0
  local invalid_count=0
  
  for workflow in .github/workflows/*.yml; do
    if [ -f "$workflow" ]; then
      # Check if file has content
      if [ -s "$workflow" ]; then
        # Basic YAML validation (check for 'name:' and 'on:')
        if grep -q "^name:" "$workflow" && grep -q "^on:" "$workflow"; then
          ((valid_count++))
        else
          echo -e "${YELLOW}⚠️  Workflow might be incomplete: $(basename $workflow)${NC}"
          ((invalid_count++))
        fi
      fi
    fi
  done
  
  echo -e "${GREEN}✅ Valid workflows: $valid_count${NC}"
  if [ $invalid_count -gt 0 ]; then
    echo -e "${YELLOW}⚠️  Potentially invalid workflows: $invalid_count${NC}"
  fi
}

# Function to generate cleanup report
generate_report() {
  echo ""
  echo -e "${YELLOW}📊 Cleanup Report${NC}"
  echo "=================================="
  echo -e "${GREEN}✅ Files deleted: $DELETED_COUNT${NC}"
  echo -e "${GREEN}✅ Files moved: $MOVED_COUNT${NC}"
  
  if [ $ERRORS -gt 0 ]; then
    echo -e "${RED}❌ Errors encountered: $ERRORS${NC}"
  fi
  
  # Count remaining workflows
  local remaining_count=$(find .github/workflows -name "*.yml" -type f 2>/dev/null | wc -l)
  echo -e "${GREEN}📁 Remaining workflows: $remaining_count${NC}"
  
  # Generate summary file
  cat > CLEANUP_SUMMARY.md << EOF
# 🧹 Cleanup Summary Report

## Date: $(date)

### Operations Performed
- **Files Deleted:** $DELETED_COUNT
- **Files Moved:** $MOVED_COUNT
- **Errors:** $ERRORS
- **Remaining Workflows:** $remaining_count

### Deleted Files
$(for file in "${EMPTY_WORKFLOWS[@]}"; do echo "- $file"; done)

### Moved Files
$(for source in "${!FILES_TO_MOVE[@]}"; do echo "- $source → ${FILES_TO_MOVE[$source]}"; done)

### Next Steps
1. Review remaining workflows for functionality
2. Update CI/CD documentation
3. Test all active workflows
4. Monitor for any issues

---
*Generated by Design System Maintenance Script v1.0.0*
EOF

  echo -e "${GREEN}✅ Report saved to CLEANUP_SUMMARY.md${NC}"
}

# Main execution
main() {
  echo "Starting cleanup process..."
  echo ""
  
  # Execute cleanup operations
  delete_empty_workflows
  echo ""
  move_misplaced_files
  echo ""
  validate_workflows
  echo ""
  generate_report
  
  echo ""
  echo -e "${GREEN}🎉 Cleanup Complete!${NC}"
  
  if [ $ERRORS -eq 0 ]; then
    echo -e "${GREEN}All operations completed successfully!${NC}"
    exit 0
  else
    echo -e "${YELLOW}Cleanup completed with $ERRORS errors. Please review.${NC}"
    exit 1
  fi
}

# Run main function
main
