import chalk from 'chalk';
import inquirer from 'inquirer';
import ora from 'ora';
import fs from 'fs/promises';
import path from 'path';

interface ThemeOptions {
  base: string;
  primary?: string;
  secondary?: string;
}

export async function generateTheme(name: string, options: ThemeOptions) {
  const spinner = ora(`Generating theme ${name}...`).start();

  try {
    // Validate theme name
    if (!/^[a-z][a-z0-9-]*$/.test(name)) {
      throw new Error('Theme name must be in kebab-case');
    }

    // Ask for theme configuration
    const answers = await inquirer.prompt([
      {
        type: 'input',
        name: 'primary',
        message: 'Primary color (hex):',
        default: options.primary || '#3b82f6',
        validate: (input) => /^#[0-9A-Fa-f]{6}$/.test(input) || 'Please enter a valid hex color',
      },
      {
        type: 'input',
        name: 'secondary',
        message: 'Secondary color (hex):',
        default: options.secondary || '#8b5cf6',
        validate: (input) => /^#[0-9A-Fa-f]{6}$/.test(input) || 'Please enter a valid hex color',
      },
      {
        type: 'input',
        name: 'background',
        message: 'Background color (hex):',
        default: '#ffffff',
        validate: (input) => /^#[0-9A-Fa-f]{6}$/.test(input) || 'Please enter a valid hex color',
      },
      {
        type: 'input',
        name: 'foreground',
        message: 'Foreground color (hex):',
        default: '#020817',
        validate: (input) => /^#[0-9A-Fa-f]{6}$/.test(input) || 'Please enter a valid hex color',
      },
      {
        type: 'confirm',
        name: 'darkMode',
        message: 'Include dark mode variant?',
        default: true,
      },
    ]);

    // Generate HSL values from hex
    const hexToHsl = (hex: string) => {
      const r = parseInt(hex.slice(1, 3), 16) / 255;
      const g = parseInt(hex.slice(3, 5), 16) / 255;
      const b = parseInt(hex.slice(5, 7), 16) / 255;

      const max = Math.max(r, g, b);
      const min = Math.min(r, g, b);
      let h = 0, s = 0, l = (max + min) / 2;

      if (max !== min) {
        const d = max - min;
        s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
        
        switch (max) {
          case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
          case g: h = ((b - r) / d + 2) / 6; break;
          case b: h = ((r - g) / d + 4) / 6; break;
        }
      }

      return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
    };

    const themeContent = `/* Theme: ${name} */
/* Generated by Dainabase UI CLI */

.theme-${name} {
  /* Light Mode */
  --background: 0 0% 100%;
  --foreground: ${hexToHsl(answers.foreground)};
  
  --card: 0 0% 100%;
  --card-foreground: ${hexToHsl(answers.foreground)};
  
  --popover: 0 0% 100%;
  --popover-foreground: ${hexToHsl(answers.foreground)};
  
  --primary: ${hexToHsl(answers.primary)};
  --primary-foreground: 0 0% 98%;
  
  --secondary: ${hexToHsl(answers.secondary)};
  --secondary-foreground: ${hexToHsl(answers.foreground)};
  
  --muted: 240 4.8% 95.9%;
  --muted-foreground: 240 3.8% 46.1%;
  
  --accent: 240 4.8% 95.9%;
  --accent-foreground: ${hexToHsl(answers.foreground)};
  
  --destructive: 0 84.2% 60.2%;
  --destructive-foreground: 0 0% 98%;
  
  --border: 240 5.9% 90%;
  --input: 240 5.9% 90%;
  --ring: ${hexToHsl(answers.primary)};
  
  --radius: 0.5rem;
}${answers.darkMode ? `

.dark .theme-${name} {
  /* Dark Mode */
  --background: 240 10% 3.9%;
  --foreground: 0 0% 98%;
  
  --card: 240 10% 3.9%;
  --card-foreground: 0 0% 98%;
  
  --popover: 240 10% 3.9%;
  --popover-foreground: 0 0% 98%;
  
  --primary: ${hexToHsl(answers.primary)};
  --primary-foreground: 240 5.9% 10%;
  
  --secondary: ${hexToHsl(answers.secondary)};
  --secondary-foreground: 0 0% 98%;
  
  --muted: 240 3.7% 15.9%;
  --muted-foreground: 240 5% 64.9%;
  
  --accent: 240 3.7% 15.9%;
  --accent-foreground: 0 0% 98%;
  
  --destructive: 0 62.8% 30.6%;
  --destructive-foreground: 0 0% 98%;
  
  --border: 240 3.7% 15.9%;
  --input: 240 3.7% 15.9%;
  --ring: ${hexToHsl(answers.primary)};
}` : ''}
`;

    // Save theme file
    const themesDir = './src/themes';
    await fs.mkdir(themesDir, { recursive: true });
    
    const themePath = path.join(themesDir, `${name}.css`);
    await fs.writeFile(themePath, themeContent);

    // Update themes index
    const indexPath = path.join(themesDir, 'index.ts');
    let indexContent = '';
    
    try {
      indexContent = await fs.readFile(indexPath, 'utf-8');
    } catch {
      indexContent = '// Theme exports\n';
    }
    
    if (!indexContent.includes(`'./src/themes/${name}.css'`)) {
      indexContent += `export './src/themes/${name}.css'\n`;
      await fs.writeFile(indexPath, indexContent);
    }

    spinner.succeed(chalk.green(`✅ Theme ${name} generated successfully!`));
    console.log(chalk.blue(`🎨 Location: ${themePath}`));
    console.log(chalk.yellow('\n📝 Next steps:'));
    console.log(`  1. Import theme: import './themes/${name}.css'`);
    console.log(`  2. Apply theme: <div className="theme-${name}">`);
    console.log('  3. Test with ThemeToggle component');
  } catch (error) {
    spinner.fail(chalk.red(`Failed to generate theme: ${error.message}`));
    process.exit(1);
  }
}