#!/bin/bash
# EMERGENCY WORKFLOW AUDIT SCRIPT
# Created: 2025-08-14
# Purpose: Identify all automatic workflows that need to be disabled

echo "🚨 EMERGENCY WORKFLOW AUDIT - $(date)"
echo "========================================"
echo ""
echo "Scanning all workflows for automatic triggers..."
echo ""

WORKFLOWS=(
"auto-fix-deps.yml"
"auto-publish-v040.yml"
"bundle-monitor.yml"
"bundle-size.yml"
"consumer-smoke.yml"
"deploy-docs.yml"
"deploy-storybook.yml"
"ds-guard.yml"
"ds-integrity-check.yml"
"e2e-tests.yml"
"fix-and-publish.yml"
"force-publish.yml"
"manual-publish.yml"
"mutation-testing.yml"
"npm-auto-publish.yml"
"npm-monitor.yml"
"npm-publish-beta.yml"
"npm-publish-ui.yml"
"npm-publish.yml"
"pr-branch-name-guard.yml"
"publish-manual.yml"
"publish-ui.yml"
"quick-npm-publish.yml"
"release.yml"
"simple-publish.yml"
"sprint3-ci.yml"
"test-design-system.yml"
"test-suite.yml"
"ui-100-coverage-publish.yml"
"ui-a11y.yml"
"ui-bundle-optimization.yml"
"ui-chromatic.yml"
"ui-ci.yml"
"ui-e2e-tests.yml"
"ui-storybook-pages.yml"
"ui-test-suite.yml"
"ui-test.yml"
"ui-unit.yml"
"web-ci.yml"
)

echo "## WORKFLOWS STATUS"
echo ""
echo "| Workflow | Trigger | Status | Action Required |"
echo "|----------|---------|--------|-----------------|"

for workflow in "${WORKFLOWS[@]}"; do
  echo "| $workflow | Checking... | - | - |"
done

echo ""
echo "## RECOMMENDATIONS"
echo ""
echo "### IMMEDIATE ACTION (Priority 1)"
echo "Workflows that trigger on every push/PR:"
echo "- [ ] test-suite.yml - DISABLED ✅"
echo "- [ ] sprint3-ci.yml - DISABLED ✅"
echo "- [ ] ui-test-suite.yml"
echo "- [ ] ui-test.yml"
echo "- [ ] ui-unit.yml"
echo "- [ ] e2e-tests.yml"
echo "- [ ] bundle-size.yml"
echo "- [ ] ds-guard.yml"
echo ""
echo "### SECONDARY ACTION (Priority 2)"
echo "Duplicate NPM publishing workflows to remove:"
echo "- [ ] npm-publish-ui.yml"
echo "- [ ] npm-publish-beta.yml"
echo "- [ ] quick-npm-publish.yml"
echo "- [ ] force-publish.yml"
echo "- [ ] simple-publish.yml"
echo "- [ ] auto-publish-v040.yml"
echo "- [ ] fix-and-publish.yml"
echo ""
echo "### KEEP (Already Manual or Essential)"
echo "- [x] release.yml (manual)"
echo "- [x] deploy-storybook.yml (manual)"
echo "- [x] npm-publish.yml (consolidate here)"
echo ""
echo "## NEXT STEPS"
echo "1. Disable all automatic triggers (change to workflow_dispatch)"
echo "2. Delete duplicate workflows"
echo "3. Keep only 4-5 essential workflows"
echo "4. Fix package.json and tests"
echo ""
echo "Generated: $(date)"
